eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    secure-port-enabled: true
    nonsecure-port-enabled: false
    nonSecurePort: 80
    securePort: 443
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${PORT}
    statusPageUrl: https://${eureka.hostname}/
    healthCheckUrl: https://${eureka.hostname}/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}/actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
